name: GH Pages deploy
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  deployments: write
  id-token: read
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: install dependencies
        run: npm i
      - name: build app
        run: |
          npm run build
          mv ./build ./_site
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
        
