name: GH Pages deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm i
      - name: build app
        run: |
          npm run build
          mv ./site ./_site
      - name: tar built site
        run: tar -czf ./github-pages build
      - uses: actions/upload-pages-artifact@v2
        
        
